apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # 1. Сначала запускается этот контейнер, чтобы подготовить файл
      initContainers:
      - name: install
        image: busybox
        command:
        - sh
        - -c
        - |
          # Копируем шаблон из ConfigMap в общую папку и заменяем имя пода
          cp /tmp/proto/index.html /workdir/index.html
          sed -i "s/POD_NAME_HERE/$HOSTNAME/g" /workdir/index.html
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: html-proto
          mountPath: /tmp/proto
        - name: workdir
          mountPath: /workdir

      # 2. Основной Nginx, который просто показывает готовый файл
      containers:
      - name: nginx
        image: nginx:1.21.6
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      
      volumes:
      - name: html-proto
        configMap:
          name: nginx-index-html
      - name: workdir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
